### PR TITLE
package: update lint, fix code

### PR DESCRIPTION
**Pull request by sam-github**

### CODE REVIEW

**Comment by sam-github** [comment]
@rmg do you have time to look at this?

In CI its failing all OS X and Windows, which is odd.

When I try to repro on Linux and OS X.. it hangs at:

```
> strong-deploy@3.1.4 pretest /home/sam/w/sn/strong-deploy
> eslint --ignore-path .gitignore .


> strong-deploy@3.1.4 test /home/sam/w/sn/strong-deploy
> tap --timeout=300 ./test/test-*.js

To http://any:thin@127.0.0.1:36688/api/services/1/deploy/default
 * [new branch]      deploy -> deploy
ok ./test/test-deploy-default-branch.js ................. 1/1
To http://127.0.0.1:37651/api/services/1/deploy/default
 * [new branch]      deploy -> deploy
ok ./test/test-deploy-from-workingdir.js ................ 1/1
To http://127.0.0.1:36021/api/services/1/deploy/default
 * [new branch]      production -> production
ok ./test/test-deploy-specific-branch.js ................ 1/1
ok ./test/test-git-deploy-auth-failure.js ............... 1/1
To http://any:thin@127.0.0.1:35025/api/services/1/deploy/default
 * [new branch]      deploy -> deploy
ok ./test/test-git-deploy-auth.js ....................... 1/1
ssh connection error:  { [Error: All configured authentication methods failed] level: 'client-authentication' }
```

AFAICT from a quick look, strong-tunnel:lib/tunnel.js is cating a connection error, `console.error()`ing it, and then ignoring it, could this be the cause of the test hang? Though why the error is ocurring IDK.

Also, better not to call console.error from a library.

**Comment by rmg** [comment]
@sam-github the Mac one's should pass on the next run, but the test should be modified to not even run on Windows.. it assumes that the user running the tests can `ssh -i ~/.ssh/id_rsa $USER@localhost`. I'm guessing you either don't have sshd running on your laptops, or your don't have `~/.ssh/id_rsa.pub` included in `~/.ssh/authorized_keys`.

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by sam-github** [comment]
@slnode test please

**Pull request merged**
